### ISSUE TITLE
V2版本

### ISSUE THREAD

**Issue by webjiazu** [pili-engineering/pili-sdk-php#45]
现在七牛官网，给出的已经是V2版本的文档了，您有意向做升级吗？ 目前我正在研究并使用七牛，希望能交个朋友

**Comment by longbai** [comment]
v2 版本 https://github.com/pili-engineering/pili-sdk-php.v2 在这里

**Comment by webjiazu** [comment]
收到，我们近期就会使用； 我们保持联系吧； 感谢
